#!/bin/bash
list=$1
doing(){
	file_script="auto_hotfix_edit"
    scp ${file_script} root@$i:"~" 
    ssh root@$i "bash ${file_script}"
}
for i in `cat ${list}`
do
	echo "###########$i##############"
    doing ${i}
done
