#!/bin/bash
# chkconfig: 2345 10 90
# description: add tap0
USER="root"
TAP_DEV_NUM=0
DESC="TAP config"

do_start() {
    if [ ! -x /usr/sbin/tunctl ];then
    	echo "/usr/sbin/tunctl was NOT found!"
    	exit 1
    fi
    tunctl -t tap$TAP_DEV_NUM -u root
    ifconfig tap$TAP_DEV_NUM up
}

do_stop(){
    ifconfig tap$TAP_DEV_NUM down
}

do_restart(){
    do_stop
    do_start
}

check_status(){
    ifconfig tap$TAP_DEV_NUM
}

case $1 in
    start)
            do_start
            ;;
    stop)
            do_stop
            ;;
    restart)
            do_restart
            ;;
    status)
          echo "Status of $DESC: "
          check_status
          exit "$?"
          ;;
    *)
          echo "Usage: $0 {start|stop|restart|status}"
          exit 1
    esac
